# Generated by Django 4.1 on 2024-06-11 20:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("www", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="place",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="trip",
            name="create",
        ),
    ]
